# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build store package"
  lane :storebuild do
    gradle(task: "clean")
    
    gradle(
      task: "assemble",
      build_type: "Release",
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => ENV['TIQR_FASTLANE_STORE_FILE'],
        "android.injected.signing.store.password" => ENV['TIQR_FASTLANE_STORE_PASS'],
        "android.injected.signing.key.alias" => ENV['TIQR_FASTLANE_KEY_ALIAS'],
        "android.injected.signing.key.password" => ENV['TIQR_FASTLANE_KEY_PASS'],
      }
    )

    copy_artifacts(
      artifacts: [Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH], File.absolute_path("../app/build/outputs/mapping/release/mapping.txt")],
      target_path: File.absolute_path("../distribution/")
    )
  end
end